namespace Tests_and_Interviews.Models.Core
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using Tests_and_Interviews.Models.Enums;

    /// <summary>
    /// Question class represents a question that can be part of a test. 
    /// It includes properties for the question text, type, score, and related options and answers.
    /// </summary>
    [Table("Questions")]
    public class Question
    {
        /// <summary>
        /// Gets or sets the unique identifier for the entity, automatically generated by the database.
        /// </summary>
        [Key]
        [Column("id")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the associated position.
        /// </summary>
        [Column("position_id")]
        public int? PositionId { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the associated test.
        /// </summary>
        [Column("test_id")]
        public int? TestId { get; set; }

        /// <summary>
        /// Gets or sets the text of the question.
        /// </summary>
        [Column("question_text")]
        [MaxLength(200)]
        public string QuestionText { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the type of the question as a string.
        /// </summary>
        [Column("question_type_string")]
        public string QuestionTypeString { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the score value associated with this question.
        /// </summary>
        [Column("question_score")]
        public float QuestionScore { get; set; }

        /// <summary>
        /// Gets or sets the answer text associated with the question.
        /// </summary>
        [Column("question_answer")]
        [MaxLength(200)]
        public string? QuestionAnswer { get; set; }

        /// <summary>
        /// Gets or sets the options for the question in JSON format, which can be used for multiple choice questions to store the available options.
        /// </summary>
        [Column("options_json")]
        [MaxLength(1000)]
        public string? OptionsJson { get; set; }

        /// <summary>
        /// Gets questionType is a computed property that converts the QuestionTypeString to the corresponding QuestionType enum value.
        /// </summary>
        [NotMapped]
        public QuestionType Type => this.QuestionTypeString switch
        {
            "SINGLE_CHOICE" => QuestionType.SINGLE_CHOICE,
            "MULTIPLE_CHOICE" => QuestionType.MULTIPLE_CHOICE,
            "TEXT" => QuestionType.TEXT,
            "TRUE_FALSE" => QuestionType.TRUE_FALSE,
            "INTERVIEW" => QuestionType.INTERVIEW,
            _ => QuestionType.TEXT
        };

        /// <summary>
        /// Gets or sets the test instance associated with this object.
        /// </summary>
        [ForeignKey("TestId")]
        public Test? Test { get; set; }

        /// <summary>
        /// Gets or sets the collection of answers associated with the current instance.
        /// </summary>
        [InverseProperty("Question")]
        public List<Answer> Answers { get; set; } = [];
    }
}