namespace Tests_and_Interviews.Models.Core
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using Tests_and_Interviews.Models.Enums;

    /// <summary>
    /// Represents an attempt by a user to complete a test, including status, timing, score, and related user and test
    /// information.
    /// </summary>
    /// 
    /// <remarks>
    /// This entity is typically used to track the progress and results of a user's test session,
    /// including when the attempt was started, completed, or rejected, as well as validation status and scoring
    /// details. It also maintains references to the associated test, user, and the collection of answers submitted
    /// during the attempt.
    /// </remarks>
    [Table("TestAttempts")]
    public class TestAttempt
    {
        /// <summary>
        /// Gets or sets is the unique identifier for the test attempt, automatically generated by the database.
        /// </summary>
        [Key]
        [Column("id")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier for the test.
        /// </summary>
        [Column("test_id")]
        public int TestId { get; set; }

        /// <summary>
        /// Gets or sets the external user identifier associated with this entity.
        /// </summary>
        [Column("external_user_id")]
        public int? ExternalUserId { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the associated user.
        /// </summary>
        [NotMapped]
        public int? UserId
        {
            get => this.ExternalUserId;
            set => this.ExternalUserId = value;
        }

        /// <summary>
        /// Gets or sets the score value associated with this entity.
        /// </summary>
        [Column("score", TypeName = "decimal(18,2)")]
        public decimal? Score { get; set; }

        /// <summary>
        /// Gets or sets the current status of the test.
        /// </summary>
        [Column("status")]
        [MaxLength(200)]
        public string Status { get; set; } = TestStatus.AVAILABLE.ToString();

        /// <summary>
        /// Gets or sets the date and time when the operation or event started.
        /// </summary>
        [Column("started_at")]
        public DateTime? StartedAt { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the operation was completed.
        /// </summary>
        [Column("completed_at")]
        public DateTime? CompletedAt { get; set; }

        /// <summary>
        /// Gets or sets the file path to the answers file associated with this entity.
        /// </summary>
        [Column("answers_file_path")]
        [MaxLength(200)]
        public string AnswersFilePath { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets a value indicating whether the entity has been validated.
        /// </summary>
        [Column("is_validated")]
        public bool IsValidated { get; set; } = false;

        /// <summary>
        /// Gets or sets the percentage score associated with this entity.
        /// </summary>
        [Column("percentage_score", TypeName = "decimal(18,2)")]
        public decimal? PercentageScore { get; set; }

        /// <summary>
        /// Gets or sets the reason provided for rejecting the entity.
        /// </summary>
        [Column("rejection_reason")]
        [MaxLength(500)]
        public string? RejectionReason { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the item was rejected.
        /// </summary>
        [Column("rejected_at")]
        public DateTime? RejectedAt { get; set; }

        /// <summary>
        /// Gets or sets the collection of answers associated with this instance.
        /// </summary>
        public List<Answer> Answers { get; set; } =[];

        /// <summary>
        /// Gets or sets the test instance associated with this object.
        /// </summary>
        [ForeignKey("TestId")]
        public Test? Test { get; set; }
        /// <summary>
        /// Gets or sets the user instance associated with this object.
        /// </summary>
        [ForeignKey("ExternalUserId")]
        public User? User { get; set; }

        /// <summary>
        /// Begins recording the test and updates the status and start time accordingly.
        /// </summary>
        /// <remarks>
        /// Sets the test status to "RECORDING" and records the current UTC time as the start
        /// time. Call this method to initiate the test recording process.</remarks>
        public void Start()
        {
            this.Status = TestStatus.IN_PROGRESS.ToString();
            this.StartedAt = DateTime.UtcNow;
        }

        /// <summary>
        /// Begins recording the test and updates the status and start time accordingly.
        /// </summary>
        /// <remarks>
        /// Sets the test status to "COMPLETED" and records the current UTC time as the completion
        /// </remarks>
        public void Submit()
        {
            this.Status = TestStatus.COMPLETED.ToString();
            this.CompletedAt = DateTime.UtcNow;
        }

        /// <summary>
        /// Begins recording the test and updates the status and start time accordingly.
        /// </summary>
        /// <remarks>
        /// Sets the test status to "REJECTED", records the current UTC time as the rejection time, and optionally
        /// </remarks>
        public void Expire()
        {
            this.Status = TestStatus.EXPIRED.ToString();
            this.CompletedAt = DateTime.UtcNow;
        }
        /// <summary>
        /// Calculates the percentage score achieved based on the current answers and the total possible points for the
        /// test.
        /// </summary>
        /// <returns>
        /// A floating-point value representing the percentage score. Returns 0 if there are no answers or the test has
        /// no questions.
        /// </returns>
        public float CalculateScore()
        {
            if (this.Answers.Count == 0 || this.Test?.Questions.Count is null or 0)
            {
                return 0f;
            }

            float maxPossible = 0f;
            foreach (var question in this.Test.Questions)
            {
                maxPossible += question.QuestionScore;
            }

            float scoreValue = (float)(this.Score ?? 0m);
            return maxPossible == 0f ? 0f : scoreValue / maxPossible * 100f;
        }
    }
}