// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tests_and_Interviews.Data;

#nullable disable

namespace Tests_and_Interviews.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tests_and_Interviews.Models.Applicant", b =>
                {
                    b.Property<int>("ApplicantId")
                        .HasColumnType("int")
                        .HasColumnName("applicant_id");

                    b.Property<decimal?>("AppTestGrade")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("app_test_grade");

                    b.Property<string>("ApplicationStatus")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("application_status");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("applied_at");

                    b.Property<decimal?>("CompanyTestGrade")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("company_test_grade");

                    b.Property<string>("CvFileUrl")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cv_file_url");

                    b.Property<decimal?>("CvGrade")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("cv_grade");

                    b.Property<decimal?>("InterviewGrade")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("interview_grade");

                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.Property<int?>("RecommendedFromCompanyId")
                        .HasColumnType("int")
                        .HasColumnName("recommended_from_company_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ApplicantId");

                    b.HasIndex("JobId");

                    b.HasIndex("RecommendedFromCompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("applicants");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Collaborator", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.HasKey("EventId", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("collaborators");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<string>("AboutUs")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("about_us");

                    b.Property<int?>("AvatarId")
                        .HasColumnType("int")
                        .HasColumnName("avatar_id");

                    b.Property<string>("BuddyDescription")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("buddy_description");

                    b.Property<string>("BuddyName")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("buddy_name");

                    b.Property<int>("CollaboratorsCount")
                        .HasColumnType("int")
                        .HasColumnName("collaborators_count");

                    b.Property<string>("CompanyLogoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("logo_picture_url");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FinalQuote")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("final_quote");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("company_name");

                    b.Property<int>("PostedJobsCount")
                        .HasColumnType("int")
                        .HasColumnName("posted_jobs_count");

                    b.Property<string>("ProfilePicturePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("profile_picture_url");

                    b.Property<string>("Scen1Answer1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scen1_answer1");

                    b.Property<string>("Scen1Answer2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scen1_answer2");

                    b.Property<string>("Scen1Answer3")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scen1_answer3");

                    b.Property<string>("Scen1Reaction1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scen1_reaction1");

                    b.Property<string>("Scen1Reaction2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scen1_reaction2");

                    b.Property<string>("Scen1Reaction3")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scen1_reaction3");

                    b.Property<string>("Scen1Text")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scen_1_text");

                    b.Property<string>("Scen2Answer1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scen2_answer1");

                    b.Property<string>("Scen2Answer2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scen2_answer2");

                    b.Property<string>("Scen2Answer3")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scen2_answer3");

                    b.Property<string>("Scen2Reaction1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scen2_reaction1");

                    b.Property<string>("Scen2Reaction2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scen2_reaction2");

                    b.Property<string>("Scen2Reaction3")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scen2_reaction3");

                    b.Property<string>("Scen2Text")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scen2_text");

                    b.HasKey("CompanyId");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Core.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("answer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptId")
                        .HasColumnType("int")
                        .HasColumnName("attempt_id");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId");

                    b.HasIndex("QuestionId");

                    b.ToTable("answers");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Core.InterviewSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_start");

                    b.Property<int?>("ExternalUserId")
                        .HasColumnType("int")
                        .HasColumnName("external_user_id");

                    b.Property<int>("InterviewerId")
                        .HasColumnType("int")
                        .HasColumnName("interviewer_id");

                    b.Property<int>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("position_id");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("score");

                    b.Property<string>("Status")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("status");

                    b.Property<string>("Video")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("video");

                    b.HasKey("Id");

                    b.HasIndex("ExternalUserId");

                    b.ToTable("interview_sessions");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Core.LeaderboardEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("leaderboard_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastRecalculationAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_recalculation_at");

                    b.Property<decimal>("NormalizedScore")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("normalized_score");

                    b.Property<int>("RankPosition")
                        .HasColumnType("int")
                        .HasColumnName("rank_position");

                    b.Property<int>("TestId")
                        .HasColumnType("int")
                        .HasColumnName("test_id");

                    b.Property<int>("TieBreakPriority")
                        .HasColumnType("int")
                        .HasColumnName("tie_break_priority");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.HasIndex("UserId");

                    b.ToTable("LeaderboardEntries");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Core.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OptionsJson")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("options_json");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("position_id");

                    b.Property<string>("QuestionAnswer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("question_answer");

                    b.Property<float>("QuestionScore")
                        .HasColumnType("real")
                        .HasColumnName("question_score");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("question_text");

                    b.Property<string>("QuestionTypeString")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("question_type");

                    b.Property<int?>("TestId")
                        .HasColumnType("int")
                        .HasColumnName("test_id");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("questions");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Core.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("test_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("tests");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Core.TestAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userTest_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswersFilePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("answers_file_path");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<int?>("ExternalUserId")
                        .HasColumnType("int")
                        .HasColumnName("external_user_id");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("bit")
                        .HasColumnName("is_validated");

                    b.Property<decimal?>("PercentageScore")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("percentage_score");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("score");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("status");

                    b.Property<int>("TestId")
                        .HasColumnType("int")
                        .HasColumnName("test_id");

                    b.HasKey("Id");

                    b.HasIndex("ExternalUserId");

                    b.HasIndex("TestId");

                    b.ToTable("test_attempts");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Core.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CvXml")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cv_xml");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int>("HostCompanyId")
                        .HasColumnType("int")
                        .HasColumnName("host_company_id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("location");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("photo");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("posted_at");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("HostCompanyId");

                    b.ToTable("events");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.JobPosting", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.Property<int?>("AmountPayed")
                        .HasColumnType("int")
                        .HasColumnName("amount_payed");

                    b.Property<int>("AvailablePositions")
                        .HasColumnType("int")
                        .HasColumnName("available_positions");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("ExperienceLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("experience_level");

                    b.Property<string>("IndustryField")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("industry_field");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("job_description");

                    b.Property<string>("JobLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("job_location");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("job_title");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("job_type");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("photo");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("posted_at");

                    b.Property<int?>("Salary")
                        .HasColumnType("int")
                        .HasColumnName("salary");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("JobId");

                    b.HasIndex("CompanyId");

                    b.ToTable("jobs");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.JobSkill", b =>
                {
                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.Property<int>("RequiredPercentage")
                        .HasColumnType("int")
                        .HasColumnName("required_percentage");

                    b.HasKey("SkillId", "JobId");

                    b.HasIndex("JobId");

                    b.ToTable("job_skills");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Recruiter", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("CompanyId");

                    b.ToTable("Recruiters");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("skill_name");

                    b.HasKey("SkillId");

                    b.ToTable("skills");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CandidateId")
                        .HasColumnType("int")
                        .HasColumnName("candidate_id");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<string>("InterviewType")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("interview_type");

                    b.Property<int>("RecruiterId")
                        .HasColumnType("int")
                        .HasColumnName("recruiter_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<int>("StatusValue")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("RecruiterId");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Applicant", b =>
                {
                    b.HasOne("Tests_and_Interviews.Models.JobPosting", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tests_and_Interviews.Models.Company", "RecommendedFromCompany")
                        .WithMany()
                        .HasForeignKey("RecommendedFromCompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Tests_and_Interviews.Models.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("RecommendedFromCompany");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Collaborator", b =>
                {
                    b.HasOne("Tests_and_Interviews.Models.Company", "Company")
                        .WithMany("Collaborators")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Tests_and_Interviews.Models.Event", "Event")
                        .WithMany("Collaborators")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Core.Answer", b =>
                {
                    b.HasOne("Tests_and_Interviews.Models.Core.TestAttempt", "TestAttempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tests_and_Interviews.Models.Core.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("TestAttempt");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Core.InterviewSession", b =>
                {
                    b.HasOne("Tests_and_Interviews.Models.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("ExternalUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Core.LeaderboardEntry", b =>
                {
                    b.HasOne("Tests_and_Interviews.Models.Core.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tests_and_Interviews.Models.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Core.Question", b =>
                {
                    b.HasOne("Tests_and_Interviews.Models.Core.Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Core.TestAttempt", b =>
                {
                    b.HasOne("Tests_and_Interviews.Models.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("ExternalUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tests_and_Interviews.Models.Core.Test", "Test")
                        .WithMany("Attempts")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Event", b =>
                {
                    b.HasOne("Tests_and_Interviews.Models.Company", "HostCompany")
                        .WithMany("Events")
                        .HasForeignKey("HostCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HostCompany");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.JobPosting", b =>
                {
                    b.HasOne("Tests_and_Interviews.Models.Company", "Company")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.JobSkill", b =>
                {
                    b.HasOne("Tests_and_Interviews.Models.JobPosting", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tests_and_Interviews.Models.Skill", "Skill")
                        .WithMany("JobSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Recruiter", b =>
                {
                    b.HasOne("Tests_and_Interviews.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Slot", b =>
                {
                    b.HasOne("Tests_and_Interviews.Models.Core.User", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tests_and_Interviews.Models.Recruiter", "Recruiter")
                        .WithMany("Slots")
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Company", b =>
                {
                    b.Navigation("Collaborators");

                    b.Navigation("Events");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Core.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Core.Test", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Core.TestAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Event", b =>
                {
                    b.Navigation("Collaborators");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.JobPosting", b =>
                {
                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Recruiter", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Tests_and_Interviews.Models.Skill", b =>
                {
                    b.Navigation("JobSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
