using PussyCats.Library.Domain;

namespace PussyCats.Library.Persistence.Configurations;

internal static class SkillCatalog
{
    // IDs 1..32 follow matchmaking's hardcoded skill IDs verbatim so existing seed/test data
    // stays consistent after the merge. IDs 33..152 are added for skills that appear only in
    // PussyCatsApp's SkillGroup definitions.
    //
    // Categories are taken from the dominant SkillGroup.GroupName the skill belongs to in the
    // PussyCatsApp source. For matchmaking-only IDs that have no group context (UI Design,
    // Architecture, Leadership, Cloud), categories are inferred from neighboring groups.
    public static readonly Skill[] Seed =
    {
        new Skill { SkillId = 1, Name = "C#", Category = "Backend Language" },
        new Skill { SkillId = 2, Name = "React", Category = "Frontend Framework" },
        new Skill { SkillId = 3, Name = "SQL", Category = "Database Management" },
        new Skill { SkillId = 4, Name = "Testing", Category = "Testing" },
        new Skill { SkillId = 5, Name = "Selenium", Category = "Testing" },
        new Skill { SkillId = 6, Name = "Docker", Category = "Containerization" },
        new Skill { SkillId = 7, Name = "Kubernetes", Category = "Orchestration" },
        new Skill { SkillId = 8, Name = "Python", Category = "Backend Language" },
        new Skill { SkillId = 9, Name = "Pandas", Category = "Data Cleaning" },
        new Skill { SkillId = 10, Name = "Machine Learning", Category = "ML Frameworks" },
        new Skill { SkillId = 11, Name = "NLP", Category = "NLP / Computer Vision" },
        new Skill { SkillId = 12, Name = "Figma", Category = "Design Tools" },
        new Skill { SkillId = 13, Name = "UI Design", Category = "Visual Design" },
        new Skill { SkillId = 14, Name = "Architecture", Category = "Leadership" },
        new Skill { SkillId = 15, Name = "Leadership", Category = "Leadership" },
        new Skill { SkillId = 16, Name = "Cloud", Category = "Cloud Platform" },
        new Skill { SkillId = 17, Name = "Flutter", Category = "Mobile" },
        new Skill { SkillId = 18, Name = "Kotlin", Category = "Mobile" },
        new Skill { SkillId = 19, Name = "Penetration Testing", Category = "Penetration Testing" },
        new Skill { SkillId = 20, Name = "SIEM", Category = "SIEM & Monitoring" },
        new Skill { SkillId = 21, Name = "Java", Category = "Backend Language" },
        new Skill { SkillId = 22, Name = "Spring Boot", Category = "Web Framework" },
        new Skill { SkillId = 23, Name = "Agile", Category = "Methodologies" },
        new Skill { SkillId = 24, Name = "Spark", Category = "Data Engineering" },
        new Skill { SkillId = 25, Name = "Go", Category = "Backend Language" },
        new Skill { SkillId = 26, Name = "PostgreSQL", Category = "Database Management" },
        new Skill { SkillId = 27, Name = "Computer Vision", Category = "NLP / Computer Vision" },
        new Skill { SkillId = 28, Name = "PyTorch", Category = "ML Frameworks" },
        new Skill { SkillId = 29, Name = "Angular", Category = "Frontend Framework" },
        new Skill { SkillId = 30, Name = "Vue.js", Category = "Frontend Framework" },
        new Skill { SkillId = 31, Name = "TypeScript", Category = "JavaScript" },
        new Skill { SkillId = 32, Name = "AWS", Category = "Cloud Platform" },

        // PussyCats SkillGroup-only skills below.
        new Skill { SkillId = 33, Name = "HTML", Category = "UI Markup" },
        new Skill { SkillId = 34, Name = "CSS", Category = "UI Markup" },
        new Skill { SkillId = 35, Name = "SCSS", Category = "UI Markup" },
        new Skill { SkillId = 36, Name = "Tailwind", Category = "UI Markup" },
        new Skill { SkillId = 37, Name = "JavaScript", Category = "JavaScript" },
        new Skill { SkillId = 38, Name = "Svelte", Category = "Frontend Framework" },
        new Skill { SkillId = 39, Name = "Git", Category = "Version Control" },
        new Skill { SkillId = 40, Name = "GitHub", Category = "Version Control" },
        new Skill { SkillId = 41, Name = "Jest", Category = "Testing" },
        new Skill { SkillId = 42, Name = "Cypress", Category = "Testing" },
        new Skill { SkillId = 43, Name = "Webpack", Category = "Build Tools" },
        new Skill { SkillId = 44, Name = "Vite", Category = "Build Tools" },
        new Skill { SkillId = 45, Name = "Parcel", Category = "Build Tools" },
        new Skill { SkillId = 46, Name = "Adobe XD", Category = "Design Tools" },
        new Skill { SkillId = 47, Name = "Zeplin", Category = "Design Collaboration" },
        new Skill { SkillId = 48, Name = "Node.js", Category = "Backend Language" },
        new Skill { SkillId = 49, Name = "ASP.NET", Category = "Web Framework" },
        new Skill { SkillId = 50, Name = "Django", Category = "Web Framework" },
        new Skill { SkillId = 51, Name = "MySQL", Category = "Database Management" },
        new Skill { SkillId = 52, Name = "MongoDB", Category = "Database Management" },
        new Skill { SkillId = 53, Name = "Redis", Category = "Database Management" },
        new Skill { SkillId = 54, Name = "REST", Category = "API Design" },
        new Skill { SkillId = 55, Name = "GraphQL", Category = "API Design" },
        new Skill { SkillId = 56, Name = "gRPC", Category = "API Design" },
        new Skill { SkillId = 57, Name = "JUnit", Category = "Testing" },
        new Skill { SkillId = 58, Name = "NUnit", Category = "Testing" },
        new Skill { SkillId = 59, Name = "pytest", Category = "Testing" },
        new Skill { SkillId = 60, Name = "Postman", Category = "Testing" },
        new Skill { SkillId = 61, Name = "Sketch", Category = "Design Tools" },
        new Skill { SkillId = 62, Name = "InVision", Category = "Design Tools" },
        new Skill { SkillId = 63, Name = "Figma Prototyping", Category = "Prototyping" },
        new Skill { SkillId = 64, Name = "Marvel", Category = "Prototyping" },
        new Skill { SkillId = 65, Name = "Axure", Category = "Prototyping" },
        new Skill { SkillId = 66, Name = "Interviews", Category = "User Research" },
        new Skill { SkillId = 67, Name = "Surveys", Category = "User Research" },
        new Skill { SkillId = 68, Name = "Usability Testing", Category = "User Research" },
        new Skill { SkillId = 69, Name = "Typography", Category = "Visual Design" },
        new Skill { SkillId = 70, Name = "Color Theory", Category = "Visual Design" },
        new Skill { SkillId = 71, Name = "Grid Systems", Category = "Visual Design" },
        new Skill { SkillId = 72, Name = "Storybook", Category = "Handoff" },
        new Skill { SkillId = 73, Name = "Google Analytics", Category = "Analytics" },
        new Skill { SkillId = 74, Name = "Hotjar", Category = "Analytics" },
        new Skill { SkillId = 75, Name = "Mixpanel", Category = "Analytics" },
        new Skill { SkillId = 76, Name = "Podman", Category = "Containerization" },
        new Skill { SkillId = 77, Name = "Docker Swarm", Category = "Orchestration" },
        new Skill { SkillId = 78, Name = "OpenShift", Category = "Orchestration" },
        new Skill { SkillId = 79, Name = "Jenkins", Category = "CI/CD" },
        new Skill { SkillId = 80, Name = "GitHub Actions", Category = "CI/CD" },
        new Skill { SkillId = 81, Name = "GitLab CI", Category = "CI/CD" },
        new Skill { SkillId = 82, Name = "CircleCI", Category = "CI/CD" },
        new Skill { SkillId = 83, Name = "Azure", Category = "Cloud Platform" },
        new Skill { SkillId = 84, Name = "Google Cloud", Category = "Cloud Platform" },
        new Skill { SkillId = 85, Name = "Terraform", Category = "Infrastructure as Code" },
        new Skill { SkillId = 86, Name = "Ansible", Category = "Infrastructure as Code" },
        new Skill { SkillId = 87, Name = "Pulumi", Category = "Infrastructure as Code" },
        new Skill { SkillId = 88, Name = "Prometheus", Category = "Monitoring" },
        new Skill { SkillId = 89, Name = "Grafana", Category = "Monitoring" },
        new Skill { SkillId = 90, Name = "Datadog", Category = "Monitoring" },
        new Skill { SkillId = 91, Name = "Scrum", Category = "Methodologies" },
        new Skill { SkillId = 92, Name = "Kanban", Category = "Methodologies" },
        new Skill { SkillId = 93, Name = "Waterfall", Category = "Methodologies" },
        new Skill { SkillId = 94, Name = "Jira", Category = "Project Tools" },
        new Skill { SkillId = 95, Name = "Trello", Category = "Project Tools" },
        new Skill { SkillId = 96, Name = "Asana", Category = "Project Tools" },
        new Skill { SkillId = 97, Name = "Risk Assessment", Category = "Risk Management" },
        new Skill { SkillId = 98, Name = "Mitigation Planning", Category = "Risk Management" },
        new Skill { SkillId = 99, Name = "Stakeholder Management", Category = "Communication" },
        new Skill { SkillId = 100, Name = "Reporting", Category = "Communication" },
        new Skill { SkillId = 101, Name = "Presentations", Category = "Communication" },
        new Skill { SkillId = 102, Name = "Cost Estimation", Category = "Budgeting" },
        new Skill { SkillId = 103, Name = "Budget Tracking", Category = "Budgeting" },
        new Skill { SkillId = 104, Name = "MS Project", Category = "Budgeting" },
        new Skill { SkillId = 105, Name = "BigQuery", Category = "Query Language" },
        new Skill { SkillId = 106, Name = "Power BI", Category = "Data Visualization" },
        new Skill { SkillId = 107, Name = "Tableau", Category = "Data Visualization" },
        new Skill { SkillId = 108, Name = "Looker", Category = "Data Visualization" },
        new Skill { SkillId = 109, Name = "R", Category = "Programming" },
        new Skill { SkillId = 110, Name = "Descriptive Statistics", Category = "Statistical Analysis" },
        new Skill { SkillId = 111, Name = "Regression", Category = "Statistical Analysis" },
        new Skill { SkillId = 112, Name = "Hypothesis Testing", Category = "Statistical Analysis" },
        new Skill { SkillId = 113, Name = "Excel", Category = "Spreadsheets" },
        new Skill { SkillId = 114, Name = "Google Sheets", Category = "Spreadsheets" },
        new Skill { SkillId = 115, Name = "OpenRefine", Category = "Data Cleaning" },
        new Skill { SkillId = 116, Name = "Firewalls", Category = "Network Security" },
        new Skill { SkillId = 117, Name = "VPN", Category = "Network Security" },
        new Skill { SkillId = 118, Name = "IDS/IPS", Category = "Network Security" },
        new Skill { SkillId = 119, Name = "TCP/IP", Category = "Network Security" },
        new Skill { SkillId = 120, Name = "Metasploit", Category = "Penetration Testing" },
        new Skill { SkillId = 121, Name = "Burp Suite", Category = "Penetration Testing" },
        new Skill { SkillId = 122, Name = "Nmap", Category = "Penetration Testing" },
        new Skill { SkillId = 123, Name = "Splunk", Category = "SIEM & Monitoring" },
        new Skill { SkillId = 124, Name = "IBM QRadar", Category = "SIEM & Monitoring" },
        new Skill { SkillId = 125, Name = "Microsoft Sentinel", Category = "SIEM & Monitoring" },
        new Skill { SkillId = 126, Name = "AES", Category = "Cryptography" },
        new Skill { SkillId = 127, Name = "RSA", Category = "Cryptography" },
        new Skill { SkillId = 128, Name = "PKI", Category = "Cryptography" },
        new Skill { SkillId = 129, Name = "TLS/SSL", Category = "Cryptography" },
        new Skill { SkillId = 130, Name = "ISO 27001", Category = "Compliance & Standards" },
        new Skill { SkillId = 131, Name = "GDPR", Category = "Compliance & Standards" },
        new Skill { SkillId = 132, Name = "NIST", Category = "Compliance & Standards" },
        new Skill { SkillId = 133, Name = "SOC 2", Category = "Compliance & Standards" },
        new Skill { SkillId = 134, Name = "Forensics", Category = "Incident Response" },
        new Skill { SkillId = 135, Name = "Malware Analysis", Category = "Incident Response" },
        new Skill { SkillId = 136, Name = "DFIR", Category = "Incident Response" },
        new Skill { SkillId = 137, Name = "TensorFlow", Category = "ML Frameworks" },
        new Skill { SkillId = 138, Name = "scikit-learn", Category = "ML Frameworks" },
        new Skill { SkillId = 139, Name = "Keras", Category = "ML Frameworks" },
        new Skill { SkillId = 140, Name = "Julia", Category = "Programming" },
        new Skill { SkillId = 141, Name = "Linear Algebra", Category = "Mathematics" },
        new Skill { SkillId = 142, Name = "Calculus", Category = "Mathematics" },
        new Skill { SkillId = 143, Name = "Probability", Category = "Mathematics" },
        new Skill { SkillId = 144, Name = "Statistics", Category = "Mathematics" },
        new Skill { SkillId = 145, Name = "NumPy", Category = "Data Engineering" },
        new Skill { SkillId = 146, Name = "Apache Spark", Category = "Data Engineering" },
        new Skill { SkillId = 147, Name = "FastAPI", Category = "Model Deployment" },
        new Skill { SkillId = 148, Name = "MLflow", Category = "Model Deployment" },
        new Skill { SkillId = 149, Name = "Hugging Face", Category = "NLP / Computer Vision" },
        new Skill { SkillId = 150, Name = "OpenCV", Category = "NLP / Computer Vision" },
        new Skill { SkillId = 151, Name = "NLTK", Category = "NLP / Computer Vision" },
        new Skill { SkillId = 152, Name = "spaCy", Category = "NLP / Computer Vision" },
    };
}
